import java.util.*;

/*
 * 
Laptop with Browser Icon
The fun and easy project “Guess the Number” is a short Java project that allows the user to guess the number generated by the computer & involves the following steps:
The system generates a random number from a given range, say 1 to 100.
The user is prompted to enter their given number in a displayed dialogue box.
The computer then tells if the entered number matches the guesses number or it is higher/lower than the generated number.
The game continues under the user guessing the number.
You can also incorporate further details as:
Limiting the number of attempts.
Adding more rounds.
Displaying score.
Giving points based on the number of attempts.
 */
public class gess {

    public static void main(String[] args) {
        Random rand = new Random();
        Scanner sc = new Scanner(System.in);
        int count = 0;
        do{
            int r= rand.nextInt(100);
            System.out.println("Guess the number :- ");
            int g = sc.nextInt();
            if (g == r){
                count ++;
                System.out.println("You gess right number ");
            }
            else{System.out.println("The right number is "+r);}

            System.out.println("Enter y/Y of continue :- ");
            char yes = sc.next().charAt(0);
            if (yes == 'y' | yes == 'Y'){continue;}
            else {System.out.println("Thank you ");break;}

        }while(true);
        System.out.println("The Total score is :- " + count);
    }
}